version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jupally123
